# Docker Compose file to run dockerfile locally

version: '3.7'

networks:
  corpo-network:
    driver: bridge

services:
  ultimate-corpo-next-js-boilerplate:
    build:
      context: ../../
      dockerfile: .docker/local/Dockerfile
    image: ultimate-corpo-next-js-boilerplate:local
    container_name: ultimate-corpo-next-js-boilerplate
    networks:
      - corpo-network
    env_file:
      - ../../.env.local
    ports:
      - '3000:3000'
